name: ci

on: [push, pull_request, release]

jobs:
  test:
    name: test migrating denosaurs on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: clone repo
        uses: actions/checkout@master
      - name: install deno
        uses: denolib/setup-deno@master
      - name: Check formatting
        run: deno fmt --check
      - name: run tests
        run: deno test
